version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - 'echo "{\"newsletter_endpoint\": \"$NEWSLETTER_ENDPOINT\"}" > env.json'
  build:
    commands:
      - zip -r code.zip .
  post_build:
    finally:
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://./code.zip
